# ВАЖЛИВО: Вимкніть Hibernate DDL
spring.jpa.hibernate.ddl-auto=none  # Тепер Liquibase керує схемою!
  
  # Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.drop-first=false  # НЕ видаляти БД при старті (небезпечно!)
  
  # Показувати SQL для відладки
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true